### ISSUE TITLE
Game crash with mod Dashloader 5.0.0 Beta 2

### ISSUE THREAD

**Issue by maurice8cf** [Boxadactle/DebugKeybind#1]
The game crashes with Dashloader installed. Tested with Fabric API, remocing Dashloader from the mod list works

**Comment by maurice8cf** [comment]
Game crashes too with Tweakermore v3.14.0 when trying to launch it

**Comment by Boxadactle** [comment]
Somehow forgot to remove an @Overwrite call, it was most likely causing the issue.
